# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a8c220cc093559b436195579b73cf93d83680d99ad6e31bb8ed669f2e34e45a238f1dc81118502078cfa260ec13aade0cb0083760595f1f14791842006f22c0

test:
  secret_key_base: 29345dc1943b3f7b63f9e5834e14638c93fbe90619cbe7748400fdae772e4235fe3c9b823b054fa625d5695a423ee6be970dae06298baf91d54ff58506e78750

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
